name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'adopt' if needed
          java-version: '17'  # Change if using a different version

      - name: Set Up Maven
        run: sudo apt-get install -y maven

      - name: Install Xvfb (For GUI Browser Execution)
        run: sudo apt-get install -y xvfb

      - name: Start Virtual Display
        run: Xvfb :99 -ac &

      - name: Set Display for Non-Headless Execution
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable
      
      - name: Install Matching ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          
      - name: Set Environment Variables
        run: echo "MAVEN_OPTS=--add-exports jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED" >> $GITHUB_ENV

      - name: Run Selenium Tests
        run: mvn clean test -Dmaven.compiler.forceJavacCompilerUse=true

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports
